In [2]:
import numpy as np
import time

In [3]:
# TODO: Use numpy to create 5 arrays:
# 1 1D vector
# 1 2D array with shape (2, 3)
# 1 2D ones array with shape (2, 3)
# 1 2D zeros array with shape(2, 3)
# 2 2D array with random values

In [15]:
# 1D vector
# Remember to print its shape
vec = np.array([1,2,3])
print(vec)
print(vec.shape)
arr = np.array([[1],[2],[3]])
print(arr)
print(arr.shape)

[1 2 3]
(3,)
[[1]
 [2]
 [3]]
(3, 1)


In [5]:
# 2D array
# Rememebr to print its shape
arr = np.array([[1,2,3],[4,5,6]])

In [16]:
# 2D ones array
# Remember to print its shape
one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# 2D zeros array
# Remember to print its shape
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Element-wise Addition


In [9]:
# Element-wise Multiplication


In [10]:
# Dot Product


In [11]:
# Create 2D array with random values of shape (1000000, 1)
rand1 = np.random.rand(1000000,1)
rand2 = np.random.rand(1000000,1)
print(rand1)

[[0.99198445]
 [0.13767856]
 [0.95770216]
 ...
 [0.12473008]
 [0.19215165]
 [0.94949724]]


In [12]:
# TODO: Use vectorization to calculate the dot product
# call time.time() twice to calculate the total run time 

In [13]:
begin = time.time()
rand2 = np.t(rand2)
print(rand2)
ans1 = rand1.T.dot(rand2)
end = time.time()

AttributeError: module 'numpy' has no attribute 't'

In [ ]:
# TODO: Use for loop to calculate the dot product
# call time.time() twice to calculate the total run time 